"""V2 domain augmentation for spam training.

Adds delivery/e-commerce/courier-style spam examples (matching MDAS's
real-world usage) to complement the SMS UCI corpus which skews toward
prize/phone-scam SMS.
"""

# (text, label) pairs. label: 1 = spam, 0 = ham
DOMAIN_PAIRS = [
    # --- delivery / courier scams (spam) ---
    ("Your package is held at customs. Pay 2.99 to release it now.", 1),
    ("DHL: rebook your delivery within 24 hours or pay a storage fee. Click here.", 1),
    ("FedEx fee settlement: your parcel was not delivered due to unpaid postage 1.79.", 1),
    ("Amazon order #A9473 refund claim. Confirm your bank details to receive 349.", 1),
    ("Hermes: your parcel address is incomplete. Update in 12 hours.", 1),
    ("URGENT: your courier missed the delivery slot. Reschedule at the link.", 1),
    ("Your order could not be delivered. Verify your address now or your items will be returned.", 1),
    ("Congratulations! Your order qualifies for a free iPhone draw. Call to claim.", 1),
    ("Invoice D2021 overdue. Pay the balance or legal action, reply with your card.", 1),
    ("Your refund of 548 is waiting. Click the link and enter your CVV to receive.", 1),
    ("Tracking update: your package was returned to sender. Confirm a reshipment fee.", 1),
    ("Reminder: delivery fee payment required before release. Immediate action needed.", 1),
    ("Win a free trip for your next order! Text ORDER to 8090 now.", 1),
    ("Your Dmart order is on hold. Pay 1.99 delivery verification to proceed.", 1),
    ("Flipkart gift voucher worth 5000 waiting for you. Contact to redeem.", 1),
    ("Myntra clearance: urgent 90% off flash sale. Use link before it closes.", 1),
    ("You have won an Amazon gift card. Reply YES to claim within 10 minutes.", 1),
    ("Delayed package? Im not with courier support, visit the official tracker.", 0),

    # --- legitimate logistics / customer service (ham) ---
    ("Your order #A9473 has been shipped. Tracking: 1Z999AA10123456784.", 0),
    ("Our courier attempted delivery today but no one was available. We will retry tomorrow.", 0),
    ("Your refund of 34.99 has been processed and will appear in 3-5 business days.", 0),
    ("The package is stuck in customs due to incomplete paperwork. Please call support.", 0),
    ("Delivery rescheduled to Saturday between 9am-1pm. Reply STOP to opt out of SMS.", 0),
    ("We see your package shows delivered but you did not receive it. We opened a claim.", 0),
    ("Your invoice is ready. Amount due: 24.99, reference INV-2024-081. No action if paid.", 0),
    ("Thank you for your order. Your estimate delivery is Thursday.", 0),
    ("The item you returned has been received and inspected. Refund on its way.", 0),
    ("Unfortunately the label was damaged and the courier could not scan it. We resent the label.", 0),

    # ---- legitimate domain ham — expanded to balance spam domain (teach model this prose is ham) ----
    ("I received the wrong item and need a replacement.", 0),
    ("How do I track my package?", 0),
    ("My delivery is running late, could you provide an update?", 0),
    ("The driver left the parcel at the front desk.", 0),
    ("Please update me when my order ships.", 0),
    ("My package shows delivered but I did not find it.", 0),
    ("Can you help me return this defective product?", 0),
    ("The refund amount seems incorrect on my statement.", 0),
    ("I would like to change my shipping address.", 0),
    ("Is my order eligible for free returns?", 0),
    ("The courier left a missed delivery card.", 0),
    ("I was charged twice for my order.", 0),
    ("Your website says delivered but I never got it.", 0),
    ("When will my replacement item be dispatched?", 0),
    ("The delivery was signed for by a neighbor.", 0),
    ("I need proof of delivery for my records.", 0),
    ("The tracking number does not work.", 0),
    ("My item arrived damaged in the packaging.", 0),
    ("Please send me a return label.", 0),
    ("The package was left in the rain and got wet.", 0),
    ("Support never replied to my email.", 0),
    ("I have been waiting 3 weeks for my order.", 0),
    ("The chatbot did not help me at all.", 0),
    ("Customer service was very helpful today.", 0),
    ("My order qualified for free shipping.", 0),
    ("The estimated delivery date changed.", 0),
    ("I selected express delivery at checkout.", 0),
    ("Please hold my package at the post office.", 0),
    ("The delivery person was friendly.", 0),
    ("I received a text about my delivery window.", 0),
    ("My address was too long and got cut off.", 0),
    ("The order confirmation email never came.", 0),
    ("Can I leave instructions for the courier?", 0),
    ("My package was forwarded to the local depot.", 0),
    ("The return was picked up yesterday.", 0),
    ("Please cancel my most recent order only.", 0),
    ("I want to cancel but keep the subscription discount.", 0),
    ("The subscription renewed but I expected it to be paused.", 0),
    ("How do I unsubscribe from marketing emails?", 0),
    ("I did not receive the promotional code.", 0),
    ("The gift message was not included.", 0),
    ("My loyalty points were not credited.", 0),
    ("The discount did not apply at checkout.", 0),
    ("I received the correct size this time.", 0),
    ("The quality of the fabric is excellent.", 0),
    ("This is my third order from your store.", 0),
    ("I left a positive review for the product.", 0),

    # ---- expanded legitimate logistics notices (ham) ----
    ("Delivery rescheduled to Saturday between 9am-1pm. Reply STOP to opt out of SMS.", 0),
    ("Your delivery window is today 2-4pm. We will send a text when the courier is near.", 0),
    ("Order confirmed. You will receive an email when it ships.", 0),
    ("We texted you a one-time code to verify your account.", 0),
    ("Your verification code is 482913. Do not share this code.", 0),
    ("Your package has been handed to the concierge.", 0),
    ("The courier left a door tag because no one answered.", 0),
    ("We attempted delivery at 3:10pm. Please reschedule or pick up at the depot.", 0),
    ("Tracking update: out for delivery now.", 0),
    ("Tracking update: in transit, on time.", 0),
    ("Tracking update: processed at sorting facility.", 0),
    ("Your return has been picked up by the courier.", 0),
    ("Estimated arrival has changed to Wednesday.", 0),
    ("Your order is being prepared for shipment.", 0),
    ("Your order has left the warehouse.", 0),
    ("Thank you for contacting support. Ticket #4821 has been created.", 0),
    ("We replied to your query. Please check your inbox.", 0),
    ("Your refund was issued. Allow 5-7 business days.", 0),
    ("A charge of 19.99 was made to your card on file.", 0),
    ("Your card was declined. Please update your payment method.", 0),
    ("We noticed unusual activity on your account. No action needed if this was you.", 0),
    ("Account verification successful. Welcome back!", 0),
    ("Your password was changed. If this was not you, contact support.", 0),
    ("New login from a new device. Approve if this was you.", 0),
    ("Your subscription is set to renew on the 5th. Manage settings anytime.", 0),
    ("You have 2 items in your cart. Complete your purchase soon.", 0),
    ("Price drop alert: your favorite item is 20% off today.", 0),
    ("Back in stock: the item you wanted is available again.", 0),
    ("Your review was published. Thank you for the feedback.", 0),
    ("A new message from the seller: 'Your item is dispatched tomorrow.'", 0),
    ("The seller responded to your question.", 0),
    ("Your wishlist item is on sale this week.", 0),
    ("Reminder: your appointment is tomorrow at 10am.", 0),
    ("Your prescription is ready for pickup.", 0),
    ("Bill due in 3 days. View the statement online.", 0),
    ("Thank you for your payment of 45.00. Receipt attached.", 0),
    ("Your monthly statement is available.", 0),
    ("Autopay was turned on for your account.", 0),
    ("Your direct deposit was received.", 0),
    ("Your tax documents are ready to download.", 0),
    ("Hi from MDAS! Weekly digest for your accounts is ready.", 0),
    ("Cannot login: password reset link sent to your email.", 0),
    ("Two-factor authentication is now enabled.", 0),
    ("Notification: silent mode is on for conversations.", 0),
    ("John replied to your support thread.", 0),
    ("The team updated your case: issue resolved.", 0),
    ("We sent a paper invoice to your address.", 0),
    ("An email confirmation has been sent to you.", 0),
    ("SMS alerts are now active for your deliveries.", 0),
    ("You can reply STOP to stop these alerts, or text HELP for help.", 0),
]